"""init schema

Revision ID: a84fc2c35eed
Revises: 
Create Date: 2025-10-26 00:35:56.624443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a84fc2c35eed'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='trendintelai'
    )
    op.create_index(op.f('ix_trendintelai_platforms_id'), 'platforms', ['id'], unique=False, schema='trendintelai')
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('brand', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='trendintelai'
    )
    op.create_index(op.f('ix_trendintelai_users_id'), 'users', ['id'], unique=False, schema='trendintelai')
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['platform_id'], ['trendintelai.platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trendintelai'
    )
    op.create_index(op.f('ix_trendintelai_categories_id'), 'categories', ['id'], unique=False, schema='trendintelai')
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_link', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('number_of_ratings', sa.Integer(), nullable=True),
    sa.Column('display_price_value', sa.Float(), nullable=True),
    sa.Column('mrp_value', sa.Float(), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=True),
    sa.Column('selling_price_value', sa.Float(), nullable=True),
    sa.Column('product_detail_with_color', sa.Text(), nullable=True),
    sa.Column('size_and_fit', sa.Text(), nullable=True),
    sa.Column('material_and_care', sa.Text(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('sentiment_overall', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('platform_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['trendintelai.categories.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['trendintelai.platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_link'),
    schema='trendintelai'
    )
    op.create_index(op.f('ix_trendintelai_products_id'), 'products', ['id'], unique=False, schema='trendintelai')
    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['trendintelai.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trendintelai'
    )
    op.create_index(op.f('ix_trendintelai_features_id'), 'features', ['id'], unique=False, schema='trendintelai')
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['trendintelai.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trendintelai'
    )
    op.create_index(op.f('ix_trendintelai_product_images_id'), 'product_images', ['id'], unique=False, schema='trendintelai')
    op.create_table('product_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('avg_rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('sentiment_overall', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['trendintelai.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trendintelai'
    )
    op.create_index(op.f('ix_trendintelai_product_snapshots_id'), 'product_snapshots', ['id'], unique=False, schema='trendintelai')
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_uid', sa.String(length=255), nullable=True),
    sa.Column('reviewer', sa.String(length=150), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('overall_sentiment', sa.JSON(), nullable=True),
    sa.Column('aspect_sentiments', sa.JSON(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['trendintelai.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='trendintelai'
    )
    op.create_index(op.f('ix_trendintelai_reviews_id'), 'reviews', ['id'], unique=False, schema='trendintelai')
    op.create_index(op.f('ix_trendintelai_reviews_review_uid'), 'reviews', ['review_uid'], unique=True, schema='trendintelai')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trendintelai_reviews_review_uid'), table_name='reviews', schema='trendintelai')
    op.drop_index(op.f('ix_trendintelai_reviews_id'), table_name='reviews', schema='trendintelai')
    op.drop_table('reviews', schema='trendintelai')
    op.drop_index(op.f('ix_trendintelai_product_snapshots_id'), table_name='product_snapshots', schema='trendintelai')
    op.drop_table('product_snapshots', schema='trendintelai')
    op.drop_index(op.f('ix_trendintelai_product_images_id'), table_name='product_images', schema='trendintelai')
    op.drop_table('product_images', schema='trendintelai')
    op.drop_index(op.f('ix_trendintelai_features_id'), table_name='features', schema='trendintelai')
    op.drop_table('features', schema='trendintelai')
    op.drop_index(op.f('ix_trendintelai_products_id'), table_name='products', schema='trendintelai')
    op.drop_table('products', schema='trendintelai')
    op.drop_index(op.f('ix_trendintelai_categories_id'), table_name='categories', schema='trendintelai')
    op.drop_table('categories', schema='trendintelai')
    op.drop_index(op.f('ix_trendintelai_users_id'), table_name='users', schema='trendintelai')
    op.drop_table('users', schema='trendintelai')
    op.drop_index(op.f('ix_trendintelai_platforms_id'), table_name='platforms', schema='trendintelai')
    op.drop_table('platforms', schema='trendintelai')
    # ### end Alembic commands ###
